### ISSUE TITLE
Reconfigure dependabot to watch correct branches

### ISSUE THREAD

**Issue by mirekys** [oarepo/invenio-integration-tests#19]
Currently dependabot reports alerts and creates PRs against the main branch, which is not used by any apps.

Can we reconfigure it to track v11 and v12 branches?

**Comment by thlava-cesnet** [comment]
[dependabot.yml](https://github.com/oarepo/invenio-integration-tests/blob/master/.github/dependabot.yml) with `target-branch: [ "rdm-11", "rdm-12" ]` installed, hope it's a solution
